version: '2'

services:
  pd1:
    image: pingcap/pd
    expose:
      - "2379"
      - "2380"
    volumes:
      - /etc/localtime:/etc/localtime:ro

    command:
      - --name=pd1
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd1:2379
      - --advertise-peer-urls=http://pd1:2380
      - --initial-cluster=pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380

    privileged: true
    restart: always
    container_name: tidb-pd1

  pd2:
    image: pingcap/pd
    expose:
      - "2379"
      - "2380"
    volumes:
      - /etc/localtime:/etc/localtime:ro

    command:
      - --name=pd2
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd2:2379
      - --advertise-peer-urls=http://pd2:2380
      - --initial-cluster=pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380

    privileged: true
    restart: always
    container_name: tidb-pd2

  pd3:
    image: pingcap/pd
    expose:
      - "2379"
      - "2380"
    volumes:
      - /etc/localtime:/etc/localtime:ro

    command:
      - --name=pd3
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd3:2379
      - --advertise-peer-urls=http://pd3:2380
      - --initial-cluster=pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380

    privileged: true
    restart: always
    container_name: tidb-pd3

  tikv1:
    image: pingcap/tikv
    expose:
      - "20160"
    volumes:
      - /etc/localtime:/etc/localtime:ro

    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv1:20160
      - --data-dir=/var/tikv
      - --pd=pd1:2379,pd2:2379,pd3:2379

    depends_on:
      - "pd1"
      - "pd2"
      - "pd3"

    entrypoint: /tikv-server

    privileged: true
    restart: always
    container_name: tidb-tikv1

  tikv2:
    image: pingcap/tikv
    expose:
      - "20160"
    volumes:
      - /etc/localtime:/etc/localtime:ro

    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv2:20160
      - --data-dir=/var/tikv
      - --pd=pd1:2379,pd2:2379,pd3:2379

    depends_on:
      - "pd1"
      - "pd2"
      - "pd3"

    entrypoint: /tikv-server

    privileged: true
    restart: always
    container_name: tidb-tikv2

  tikv3:
    image: pingcap/tikv
    expose:
      - "20160"
    volumes:
      - /etc/localtime:/etc/localtime:ro

    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv3:20160
      - --data-dir=/var/tikv
      - --pd=pd1:2379,pd2:2379,pd3:2379

    depends_on:
      - "pd1"
      - "pd2"
      - "pd3"

    entrypoint: /tikv-server

    privileged: true
    restart: always
    container_name: tidb-tikv3

  tidb:
    image: pingcap/tidb
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - /etc/localtime:/etc/localtime:ro

    command:
      - --store=tikv
      - --path=pd1:2379,pd2:2379,pd3:2379
      - -L=warn

    depends_on:
      - "tikv1"
      - "tikv2"
      - "tikv3"

    privileged: true
    restart: always
    container_name: tidb-tidb